# ============================================================================
# File: llm_models.py
# Author: J.W. de Roode
# GitHub: https://github.com/Wesseldr
# Project: Agentic Invoice Processor – Google AI 5-Day Intensive
# Created: 2025-11-30
# Description:
#     Pydantic data models defining the schema for invoice headers, line items,
#     and overall results. Ensures type safety and output validation.
# ============================================================================

"""
Data Models Module
==================

This module defines the Pydantic data structures used to enforce strict schema validation
on the output generated by the LLM Agents. It serves as the contract between the
probabilistic AI layer and the deterministic application logic.

Key Models:
- **InvoiceLLMResult:** The root object containing all extracted data.
- **InvoiceHeader:** Administrative metadata (Supplier, Date, Totals).
- **ClientCase:** Detailed line items representing billable sessions.
"""
from typing import List, Optional
from pydantic import BaseModel


class InvoiceHeader(BaseModel):
    """
    Represents administrative metadata extracted from the invoice header or footer.
    
    Attributes:
        supplierName (str): Name of the service provider (e.g., 'Praktijk X').
        invoiceNumber (str): The unique identifier of the invoice.
        invoiceDate (str): The date of the invoice in ISO 8601 format (YYYY-MM-DD).
        kvkNumber (str): Chamber of Commerce number (8 digits).
        vatNumber (str): VAT identification number (e.g., NL...B01).
    """
    supplierName: Optional[str] = None
    invoiceNumber: Optional[str] = None
    invoiceDate: Optional[str] = None  # ISO 'YYYY-MM-DD'
    kvkNumber: Optional[str] = None
    vatNumber: Optional[str] = None


class ClientCase(BaseModel):
    """
    Represents a single billable line item (coaching session or service).
    
    This model distinguishes between the raw text found on the invoice (which may contain typos)
    and the validated ID matched against the internal database.

    Attributes:
        validatedClientCaseNumber (str): The canonical, corrected ID from the database (e.g., 'ZU16-I25-555').
                                         This is the value used for final processing.
        rawClientCaseNumber (str): The exact text originally found on the PDF (e.g., 'ZU16-125-555').
                                   Stored for audit trails and debugging.
        date (str): Date of the session in ISO 8601 format (YYYY-MM-DD).
        durationHours (float): Duration of the session in hours (decimal).
    """
    validatedClientCaseNumber: str 
    rawClientCaseNumber: Optional[str] = None 
    date: Optional[str] = None  # ISO 'YYYY-MM-DD'
    durationHours: Optional[float] = None


class InvoiceLLMResult(BaseModel):
    """
    The root schema for the structured output returned by the Invoice Agent.
    
    This object aggregates the header metadata and the list of line items.
    It acts as the single source of truth for the post-processing pipeline.

    Attributes:
        invoiceHeader (InvoiceHeader): Metadata about the invoice document.
        isCoachingInvoice (bool): Flag indicating if this is a valid coaching invoice (True) or unrelated (False).
        clientCases (List[ClientCase]): List of active, billable sessions found on the invoice.
        clientCasesNoActivity (List[str]): List of client case IDs mentioned on the invoice but explicitly marked
                                           as having no billable activity (0 hours/euros).
    """
    invoiceHeader: InvoiceHeader
    isCoachingInvoice: bool
    clientCases: List[ClientCase]
    clientCasesNoActivity: List[str] = []
